#!/bin/bash
#
# Author: Chen Tian
# Date: Mar 18, 2015

target=(Carmel-3 Carmel-4 Carmel-5 Carmel-6)

cmd=$(</dev/stdin)



for t in ${target[@]}; do
echo "Sending command to $t.........."
ssh  $t "cd ~/git/tachyon; $cmd"
done

